apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wvypmwuot-nodejs 
  janus-idp.io/tekton: wvypmwuot-nodejs
  backstage.io/kubernetes-id: wvypmwuot-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wvypmwuot-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  